version: "2"
services:
  rr:
    image: nickblair/rightresult:latest
    depends_on:
      - deps
    ports:
      - "8080:8085"
    env_file:
      - .env
    environment:
      - NEO4JURL=http://neo4j:7474/db/data
      - EVENTSTOREURL=tcp://eventstore:1113
      - ELASTICSEARCHURL=http://elasticsearch:9200
      - CLIENTHOST=http://localhost:8080

  deps:
    image: busybox:latest
    depends_on:
      - eventstore
      # - elasticsearch
      - neo4j

  eventstore:
    image: eventstore/eventstore
    volumes:
      - eventstore_volume:/var/lib/eventstore
    # volumes:
    # - ./eventstore/data:/var/lib/eventstore
    # - ./eventstore/log:/var/log/eventstore
    # environment:
    #   - EVENTSTORE_START_STANDARD_PROJECTIONS=true
    ports:
      - "1113:1113"
      - "2113:2113"

  neo4j:
    image: neo4j:3.4.1
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
      # - NEO4J_DEFAULT_LISTEN_ADDRESS=0.0.0.0

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
  #   environment:
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - xpack.security.enabled=false
  #     - ES_JAVA_OPTS=-Xms512m -Xmx512m
  #     - http.host=0.0.0.0
  #     - transport.host=127.0.0.1
  #     # - ES_JAVA_OPTS=-Xms1g -Xmx1g
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   # volumes:
  #   #   - ./elasticsearch:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  # # kibana:
  # #   image: docker.elastic.co/kibana/kibana:6.2.3
  # #   ports:
  # #     - 5601:5601

volumes:
  eventstore_volume:
    driver: local
