POST https://rightresu.lt/api/appendFixtureToGameweek
content-type: application/json

{
  "FixtureSetId": "1b4cd150-b562-4986-bd3a-87a87a708805",
  "Home": "Norwich",
  "Away": "Chelsea",
  "KickOff": "2022-03-10T19:30:00",
}
