POST https://rightresu.lt/api/removeOpenFixture
content-type: application/json

{
    "FixtureSetId": "9919845c-693f-4593-a5fb-2d5956c5cfc3",
    "FixtureId": "f277b57c-ec24-4889-b7fc-bee09ab5f36d",
}
