name: Publish

on:
  push:
    branches:
      - master

env:
  publish_version: 0.0.${{ github.run_number }}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: [3.1.300]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - run: yarn
      - run: dotnet tool restore
      - run: dotnet paket restore
      - run: dotnet fake build -t bundle

      - uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.publish_version }}
          draft: false
          prerelease: false

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: nickblair/rightresult
          tags: latest, ${{ env.publish_version }}

      - run: ssh ${{ secrets.DEPLOY_DEST }} docker-compose stop rr
      - run: ssh ${{ secrets.DEPLOY_DEST }} docker-compose pull rr
      - run: ssh ${{ secrets.DEPLOY_DEST }} docker-compose up -d deps
      - run: sleep 15
      - run: ssh ${{ secrets.DEPLOY_DEST }} docker-compose up -d rr
