name: Publish

on:
  push:
    branches:
      - master
      - fable3

env:
  publish_version: 2022-${{ github.run_number }}

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x

      - run: npm install
      - run: dotnet tool restore
      - run: dotnet paket restore
      - run: dotnet run -- bundle
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.publish_version }}
          draft: false
          prerelease: false

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: nickblair/rightresult
          tags: latest, ${{ env.publish_version }}
